/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as ProyectosRouteImport } from './routes/proyectos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PresupuestosIndexRouteImport } from './routes/presupuestos.index'
import { Route as PresupuestosViviendaRouteImport } from './routes/presupuestos.vivienda'
import { Route as PresupuestosPromotoraRouteImport } from './routes/presupuestos.promotora'
import { Route as PresupuestosGenericoRouteImport } from './routes/presupuestos.generico'
import { Route as PresupuestoTokenRouteImport } from './routes/presupuesto.$token'
import { Route as LegalPrivacidadRouteImport } from './routes/legal.privacidad'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalAvisoRouteImport } from './routes/legal.aviso'

const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosRoute = ProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresupuestosIndexRoute = PresupuestosIndexRouteImport.update({
  id: '/presupuestos/',
  path: '/presupuestos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresupuestosViviendaRoute = PresupuestosViviendaRouteImport.update({
  id: '/presupuestos/vivienda',
  path: '/presupuestos/vivienda',
  getParentRoute: () => rootRouteImport,
} as any)
const PresupuestosPromotoraRoute = PresupuestosPromotoraRouteImport.update({
  id: '/presupuestos/promotora',
  path: '/presupuestos/promotora',
  getParentRoute: () => rootRouteImport,
} as any)
const PresupuestosGenericoRoute = PresupuestosGenericoRouteImport.update({
  id: '/presupuestos/generico',
  path: '/presupuestos/generico',
  getParentRoute: () => rootRouteImport,
} as any)
const PresupuestoTokenRoute = PresupuestoTokenRouteImport.update({
  id: '/presupuesto/$token',
  path: '/presupuesto/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacidadRoute = LegalPrivacidadRouteImport.update({
  id: '/legal/privacidad',
  path: '/legal/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAvisoRoute = LegalAvisoRouteImport.update({
  id: '/legal/aviso',
  path: '/legal/aviso',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/empresa': typeof EmpresaRoute
  '/login': typeof LoginRoute
  '/proyectos': typeof ProyectosRoute
  '/servicios': typeof ServiciosRoute
  '/legal/aviso': typeof LegalAvisoRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacidad': typeof LegalPrivacidadRoute
  '/presupuesto/$token': typeof PresupuestoTokenRoute
  '/presupuestos/generico': typeof PresupuestosGenericoRoute
  '/presupuestos/promotora': typeof PresupuestosPromotoraRoute
  '/presupuestos/vivienda': typeof PresupuestosViviendaRoute
  '/presupuestos/': typeof PresupuestosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/empresa': typeof EmpresaRoute
  '/login': typeof LoginRoute
  '/proyectos': typeof ProyectosRoute
  '/servicios': typeof ServiciosRoute
  '/legal/aviso': typeof LegalAvisoRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacidad': typeof LegalPrivacidadRoute
  '/presupuesto/$token': typeof PresupuestoTokenRoute
  '/presupuestos/generico': typeof PresupuestosGenericoRoute
  '/presupuestos/promotora': typeof PresupuestosPromotoraRoute
  '/presupuestos/vivienda': typeof PresupuestosViviendaRoute
  '/presupuestos': typeof PresupuestosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/empresa': typeof EmpresaRoute
  '/login': typeof LoginRoute
  '/proyectos': typeof ProyectosRoute
  '/servicios': typeof ServiciosRoute
  '/legal/aviso': typeof LegalAvisoRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacidad': typeof LegalPrivacidadRoute
  '/presupuesto/$token': typeof PresupuestoTokenRoute
  '/presupuestos/generico': typeof PresupuestosGenericoRoute
  '/presupuestos/promotora': typeof PresupuestosPromotoraRoute
  '/presupuestos/vivienda': typeof PresupuestosViviendaRoute
  '/presupuestos/': typeof PresupuestosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/empresa'
    | '/login'
    | '/proyectos'
    | '/servicios'
    | '/legal/aviso'
    | '/legal/cookies'
    | '/legal/privacidad'
    | '/presupuesto/$token'
    | '/presupuestos/generico'
    | '/presupuestos/promotora'
    | '/presupuestos/vivienda'
    | '/presupuestos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/empresa'
    | '/login'
    | '/proyectos'
    | '/servicios'
    | '/legal/aviso'
    | '/legal/cookies'
    | '/legal/privacidad'
    | '/presupuesto/$token'
    | '/presupuestos/generico'
    | '/presupuestos/promotora'
    | '/presupuestos/vivienda'
    | '/presupuestos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/empresa'
    | '/login'
    | '/proyectos'
    | '/servicios'
    | '/legal/aviso'
    | '/legal/cookies'
    | '/legal/privacidad'
    | '/presupuesto/$token'
    | '/presupuestos/generico'
    | '/presupuestos/promotora'
    | '/presupuestos/vivienda'
    | '/presupuestos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EmpresaRoute: typeof EmpresaRoute
  LoginRoute: typeof LoginRoute
  ProyectosRoute: typeof ProyectosRoute
  ServiciosRoute: typeof ServiciosRoute
  LegalAvisoRoute: typeof LegalAvisoRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalPrivacidadRoute: typeof LegalPrivacidadRoute
  PresupuestoTokenRoute: typeof PresupuestoTokenRoute
  PresupuestosGenericoRoute: typeof PresupuestosGenericoRoute
  PresupuestosPromotoraRoute: typeof PresupuestosPromotoraRoute
  PresupuestosViviendaRoute: typeof PresupuestosViviendaRoute
  PresupuestosIndexRoute: typeof PresupuestosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos': {
      id: '/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presupuestos/': {
      id: '/presupuestos/'
      path: '/presupuestos'
      fullPath: '/presupuestos/'
      preLoaderRoute: typeof PresupuestosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presupuestos/vivienda': {
      id: '/presupuestos/vivienda'
      path: '/presupuestos/vivienda'
      fullPath: '/presupuestos/vivienda'
      preLoaderRoute: typeof PresupuestosViviendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presupuestos/promotora': {
      id: '/presupuestos/promotora'
      path: '/presupuestos/promotora'
      fullPath: '/presupuestos/promotora'
      preLoaderRoute: typeof PresupuestosPromotoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presupuestos/generico': {
      id: '/presupuestos/generico'
      path: '/presupuestos/generico'
      fullPath: '/presupuestos/generico'
      preLoaderRoute: typeof PresupuestosGenericoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presupuesto/$token': {
      id: '/presupuesto/$token'
      path: '/presupuesto/$token'
      fullPath: '/presupuesto/$token'
      preLoaderRoute: typeof PresupuestoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacidad': {
      id: '/legal/privacidad'
      path: '/legal/privacidad'
      fullPath: '/legal/privacidad'
      preLoaderRoute: typeof LegalPrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/aviso': {
      id: '/legal/aviso'
      path: '/legal/aviso'
      fullPath: '/legal/aviso'
      preLoaderRoute: typeof LegalAvisoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EmpresaRoute: EmpresaRoute,
  LoginRoute: LoginRoute,
  ProyectosRoute: ProyectosRoute,
  ServiciosRoute: ServiciosRoute,
  LegalAvisoRoute: LegalAvisoRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalPrivacidadRoute: LegalPrivacidadRoute,
  PresupuestoTokenRoute: PresupuestoTokenRoute,
  PresupuestosGenericoRoute: PresupuestosGenericoRoute,
  PresupuestosPromotoraRoute: PresupuestosPromotoraRoute,
  PresupuestosViviendaRoute: PresupuestosViviendaRoute,
  PresupuestosIndexRoute: PresupuestosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
