/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as ProyectosRouteImport } from './routes/proyectos'
import { Route as PresupuestosRouteImport } from './routes/presupuestos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PresupuestosPromotoraRouteImport } from './routes/presupuestos.promotora'

const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosRoute = ProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const PresupuestosRoute = PresupuestosRouteImport.update({
  id: '/presupuestos',
  path: '/presupuestos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresupuestosPromotoraRoute = PresupuestosPromotoraRouteImport.update({
  id: '/promotora',
  path: '/promotora',
  getParentRoute: () => PresupuestosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/empresa': typeof EmpresaRoute
  '/login': typeof LoginRoute
  '/presupuestos': typeof PresupuestosRouteWithChildren
  '/proyectos': typeof ProyectosRoute
  '/servicios': typeof ServiciosRoute
  '/presupuestos/promotora': typeof PresupuestosPromotoraRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/empresa': typeof EmpresaRoute
  '/login': typeof LoginRoute
  '/presupuestos': typeof PresupuestosRouteWithChildren
  '/proyectos': typeof ProyectosRoute
  '/servicios': typeof ServiciosRoute
  '/presupuestos/promotora': typeof PresupuestosPromotoraRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/empresa': typeof EmpresaRoute
  '/login': typeof LoginRoute
  '/presupuestos': typeof PresupuestosRouteWithChildren
  '/proyectos': typeof ProyectosRoute
  '/servicios': typeof ServiciosRoute
  '/presupuestos/promotora': typeof PresupuestosPromotoraRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/empresa'
    | '/login'
    | '/presupuestos'
    | '/proyectos'
    | '/servicios'
    | '/presupuestos/promotora'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/empresa'
    | '/login'
    | '/presupuestos'
    | '/proyectos'
    | '/servicios'
    | '/presupuestos/promotora'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/empresa'
    | '/login'
    | '/presupuestos'
    | '/proyectos'
    | '/servicios'
    | '/presupuestos/promotora'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EmpresaRoute: typeof EmpresaRoute
  LoginRoute: typeof LoginRoute
  PresupuestosRoute: typeof PresupuestosRouteWithChildren
  ProyectosRoute: typeof ProyectosRoute
  ServiciosRoute: typeof ServiciosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos': {
      id: '/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presupuestos': {
      id: '/presupuestos'
      path: '/presupuestos'
      fullPath: '/presupuestos'
      preLoaderRoute: typeof PresupuestosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presupuestos/promotora': {
      id: '/presupuestos/promotora'
      path: '/promotora'
      fullPath: '/presupuestos/promotora'
      preLoaderRoute: typeof PresupuestosPromotoraRouteImport
      parentRoute: typeof PresupuestosRoute
    }
  }
}

interface PresupuestosRouteChildren {
  PresupuestosPromotoraRoute: typeof PresupuestosPromotoraRoute
}

const PresupuestosRouteChildren: PresupuestosRouteChildren = {
  PresupuestosPromotoraRoute: PresupuestosPromotoraRoute,
}

const PresupuestosRouteWithChildren = PresupuestosRoute._addFileChildren(
  PresupuestosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EmpresaRoute: EmpresaRoute,
  LoginRoute: LoginRoute,
  PresupuestosRoute: PresupuestosRouteWithChildren,
  ProyectosRoute: ProyectosRoute,
  ServiciosRoute: ServiciosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
